// Generated by CoffeeScript 1.3.3

(function($, require) {
  var Instagram, test;
  Instagram = require.Instagram;
  test = new Instagram({
    client_id: 'a6a557833e75443ab06c9250e47b5524',
    redirect_uri: 'http://localhost/xampp/projects/Instagram-JS-SDK/',
    scrope: 'basic+comments+relationships+likes',
    response_type: 'token'
  });
  return $('button').click(function() {
    return test.auth();
  });
})(jQuery, window);
