// Generated by CoffeeScript 1.3.3

(function($, exports) {
  var Instagram;
  Instagram = (function() {

    function Instagram(options) {
      var params;
      this.endPoint = 'https://instagram.com/oauth/authorize/?';
      params = '';
      $.each(options, function(key, value) {
        return params += key + '=' + value + '&';
      });
      this.authUri = this.endPoint + params;
    }

    Instagram.prototype.auth = function() {
      return window.location.href = this.authUri;
    };

    Instagram.prototype.getToken = function() {
      return window.location.hash.replace('#access_token=', '');
    };

    Instagram.prototype.fetch = function(url, params) {};

    Instagram.prototype.test = function(o) {
      return console.log(o);
    };

    return Instagram;

  })();
  return exports.Instagram = Instagram;
})(jQuery, window);
